services:
  mysql:
    container_name: mysql-car-rental
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental
    volumes:
      - car_rental_mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - car-rental-network
    restart: unless-stopped

  keycloak:
    container_name: keycloak-car-rental
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - car-rental-network
    command:
      - "start-dev"
    volumes:
      - car_rental_keycloak_data:/opt/keycloak/data/
    restart: unless-stopped

networks:
  car-rental-network:
    driver: bridge

volumes:
  car_rental_mysql_data:
    driver: local
  car_rental_keycloak_data:
    driver: local